### ISSUE TITLE
Rhino Issue:  Regarding the iOS, I have error message below, when I try to add my custom rhn file into my Xcode project: porcupineError(Porcupine.PorcupineError.invalidArgument(message: "Model file at does not exist at \'\'"))

### ISSUE THREAD

**Issue by edahn777** [Picovoice/rhino#115]
[](url)Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced [independently.)]([url]([url](url)))

**Comment by dbartle** [comment]
**You need to fill in the issue template!** You did not give us enough details to reproduce the issue. The template is there so that people can help you and so that you can do as much on your own first to respect the time of others.

If you are trying to learn how to use a custom file, start with the demos on this repository and if that does not work, file an issue (properly).

**Comment by edahn777** [comment]
Regarding the iOS, I have error message below, when I try to add my custom rhn file into my Xcode project: porcupineError(Porcupine.PorcupineError.invalidArgument(message: "Model file at does not exist at \'\'"))

**Comment by edahn777** [comment]
Regarding the iOS, I have error message below, when I try to add my custom
rhn file into my Xcode project:
porcupineError(Porcupine.PorcupineError.invalidArgument(message: "Model
file at does not exist at \'\'"))

Would you let me know how can I fix this issue?


2021년 6월 22일 (화) 오전 1:37, David Bartle ***@***.***>님이 작성:
