### ISSUE TITLE
Define keyword to separate multiple intents in one voice command

### ISSUE THREAD

**Issue by Jonas2OO3** [Picovoice/rhino#159]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to give multiple commands to Rhino without having to say the wake word again each time.

**Describe the solution you'd like**
I guess the title says it all: allow the user to define a keyword for a Rhino context that can be used to separate multiple intents in one voice command. Could be a keyword that is then forbidden to be used in any intent or slot, to make it easier?

**Describe alternatives you've considered**
No idea.

**Additional context**
As I have Audio feedback when processing intents, currently I always have to wait for that to finish before I can say the wake word again or it would interfere with the voice command.

**Comment by dbartle** [comment]
I believe that what you're describing can be accomplished by arranging the Porcupine and Rhino engines together in a custom manner and using multiple rhino contexts and/or porcupine keywords. The typical porcupine (wake word) -> rhino -> porcupine loop is the default offered by the Picovoice SDK. But since both engines are available separately, you can use them together in whatever configuration you would like.

For example, if the Rhino follow-on command wasn't understood the first time, you could immediately re-run rhino instead of returning to wake word detection. Since your use case is bespoke, you need to put the state machine together yourself and have your own logic decide which engine is active at which state (in other words, which engine are audio frames being sent to). You can also have multiple instances of each engine, so that they can listen for different commands.
