### ISSUE TITLE
[WEB] weird behavior (indexedDB)

### ISSUE THREAD

**Issue by tempo-riz** [Picovoice/rhino#467]
Okay I have become crazy about this issue, let me explain : 
I created a custom contex (.rhn file) downloaded it and tried it as showed in the demo, everything is working fine,
until I update the model...

My home pc runs on windows, I use the updated model, but the changes didnt take effect (still using the old one)
I push to git my changes i'll find out later...
My laptop runs on linux, I pull my changes, and here I have my latests changes !?
I checked everything many times, tried to use any combinaisons of base64 or file to pass models
Finally I noticed in doc that models are saved in indexed db, so I tried clearing it :
`indexedDB.deleteDatabase('pv_db')`
and everything worked as expected...

[same reason](https://github.com/Picovoice/picovoice/issues/503#event-8602759974)

So it seems it was still using the old stored version, for users workflow it can be a bit confusing !

### Steps to reproduce the behaviour
- create a custom context, download it
- use it with web demo
- update the context via the console, download it again, replace the old one

**Comment by ErisMik** [comment]
Although the models for Picovoice's engines are tiny for voice AI, the fetch & base64 processes on them can be expensive. In order to maximize performance the engines cache the model in IndexedDB by default, as you have seen. For most users this is the desired behaviour, since models and contexts aren't expected to change often and those providing voice enabled products won't want to waste bandwidth unnecessarily. 

For users such as yourself that perhaps want quick iteration, there is an additional element `forceWrite` you can add when you pass in the context or model into the engine (fetch or base64) that will ignore the cached version and write the new one in anyways:

```javascript
const rhino = await RhinoWorker.create(
   accessKey: "${ACCESS_KEY}",
   { base64: contextFileBase64, forceWrite: true},
   rhinoInferenceCallback,
   { base64: modelFileBase64},
);
```

The relevant documentation is located here: https://picovoice.ai/docs/api/rhino-web/#rhinomodel

This is the recommended approach instead of deleting the entire indexedDB database.

Those who are looking for a more "production-ready" approach can use the `version` element, which will only overwrite the model if the `version` number is greater than the cached on.
