### ISSUE TITLE
How to dynamically configure training files?

### ISSUE THREAD

**Issue by fanmingyi** [Picovoice/rhino#587]
Rhino Speech-to-Intent is a great project. We have a requirement: Our commercial application  is developed in such a way that each user has their own contact list, and users can speak out the names of their contacts to find the corresponding person. However, Rhino is unable to dynamically configure for each user. Is there a solution for this? Or can an API be provided to dynamically generate training files?

**Comment by laves** [comment]
@fanmingyi - thank you for your interest. Unfortunately, this is not currently possible with Rhino and is not a feature on our immediate roadmap. You may want to investigate using our [Cheetah](https://github.com/Picovoice/cheetah) or [Leopard](https://github.com/Picovoice/leopard) projects for doing speech-to-text instead. They would still have static language models but could capture a wide range of common names. Otherwise, if you are an enterprise user, please reach out to us via email and we can see what solutions are possible.
