### ISSUE TITLE
Chaining rhino inferences together

### ISSUE THREAD

**Issue by jalen-launchpad** [Picovoice/rhino#76]
Hi, I'm trying to do a series of rhino inferences chained triggered by porcupine.  So for example:

"Porcupine" -> "turn the lights on in the living room" -> "turn the lights in the living room blue" -> "turn off the lights in the kitchen" -> timeout -> Porcupine listening

I'm struggling with an error in AudioRecord start() with status code -38.  My guess is that there's two things trying to use audio at the same time?  

Currently in the RhinoManager callback, depending on inference results, I'm setting an observable integer that corresponds to whether rhino or porcupine should be running. The chaining works a few times before I get this status code. Any suggestions?

**Comment by kenarsa** [comment]
whats the platform?

**Comment by jalen-launchpad** [comment]
Oh sorry - Android!

**Comment by jalen-launchpad** [comment]
I don't know if this is by design or not, but switching between the rhino and porcupine high-level managers is what gave the status code issue.  I made sure to run porcupineManager.stop() or wait until the end of rhinoManager's callback before running porcupineManager.start() or rhinoManager.process(), but still got the error message.

I got the rhino chaining to work as intended by rewriting parts of the PicovoiceManager file from the Picovoice SDK, but using both high-level managers didn't work as I expected.  If I'm not the only one who ran into this issue with using both high-level managers, might be a nuance to consider for documentation.

**Comment by laves** [comment]
Glad you managed to make it work for you!

One note: we would not recommend running a PorcupineManager and RhinoManager back-to-back within the same app. The reason is exactly as you pointed out - it will cause issues with audio session sharing/syncing. Over in the [Picovoice repo](https://github.com/Picovoice/picovoice), we offer PicovoiceManager which combines the two engines with an audio manager. If you have a custom arrangement of the engines, like your use-case, we would probably recommend separating the audio code and the speech engines. In general, it's better practice to manage your app's audio from one point when possible. We'll add this to docs - thanks!
