### ISSUE TITLE
React-native - Continuous processing

### ISSUE THREAD

**Issue by Vincz** [Picovoice/rhino#89]
**Is your feature request related to a problem? Please describe.**
At the moment, when using `RhinoManager`, as soon as an intent is proceed, the `VoiceProcessor` is stopped and we have to launch it again (via `manager.process()` with a delay). So to listen continuously, the record will start and stop and start, etc...

**Describe the solution you'd like**
It would be great to have an option to listen continuously so after an intent, it does not call `await this._voiceProcessor.stop();`  
It would be just a little option to the `process` method.

I'm willing to post a PR if needed.

**Comment by kenarsa** [comment]
Thank you for offering the PR. I think always-listening Rhino is something that can be implemented using the lower-level API as well (i.e. `Rhino` rather than `RhinoManager`). I don't want to offer out of the box support for it in the SDK as it needs to be carefully considered on a case-by-case basis. For all practical use cases I've seen so far if you are doing always-listening voice commands you are better off using Porcupine.

**Comment by Vincz** [comment]
Yes, but Porcupine doesn't allow to generate models with short words. My use case is quite simple. I just need to react to words: "start", "stop" and "restart" and for example "Stop" is too short. Is there a way to bypass this limitation?
Also, generating model for ios seems to be restricted.

**Comment by adigujjar** [comment]
@Vincz Did you find any solution?

**Comment by adigujjar** [comment]
I also face same issue
